###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '..:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=dev@123
            - MYSQL_DATABASE=rbplanejamento_db
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev@123
        ports:
            - '2004:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '..:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2002:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '..:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
